from turtle import *

my_turtle = Turtle()
my_turtle.speed(0)
my_turtle.screen.setup(1200, 800)

# рисуем панцирь
my_turtle.color('brown')
my_turtle.width(2)
my_turtle.right(-70)
my_turtle.forward(10)
my_turtle.right(-40)
my_turtle.forward(50)
my_turtle.right(-20)
my_turtle.circle(200, 100, 70)
my_turtle.forward(50)
# рисуем тело
my_turtle.color('black')
my_turtle.width(1)
my_turtle.left(60)
my_turtle.backward(150)
my_turtle.circle(-50, -180)
my_turtle.left(-90)
my_turtle.forward(20)
my_turtle.left(-90)
my_turtle.forward(150)
my_turtle.circle(90, 60, 170)
my_turtle.left(-90)
my_turtle.forward(70)
my_turtle.right(-100)
my_turtle.forward(50)
my_turtle.right(-80)
my_turtle.forward(70)
my_turtle.left(-100)
my_turtle.circle(400, 30, 70)
my_turtle.left(-90)
my_turtle.forward(50)
my_turtle.left(80)
my_turtle.forward(50)
my_turtle.left(100)
my_turtle.forward(60)
my_turtle.right(100)
my_turtle.circle(60, 60, 70)
my_turtle.right(30)
my_turtle.forward(60)
my_turtle.left(130)
my_turtle.forward(53)
my_turtle.color('brown')
my_turtle.width(2)
my_turtle.left(40)
my_turtle.circle(-450, 47, 70)
# рисуем глаз
my_turtle.penup()
my_turtle.goto(-450, 150)
my_turtle.pendown()
my_turtle.color('red')
my_turtle.fillcolor('green')
my_turtle.begin_fill()
my_turtle.circle(5)
my_turtle.end_fill()
# рисуем линии на панцире
my_turtle.penup()
my_turtle.goto(-265, 100)
my_turtle.color('brown')
my_turtle.pendown()
my_turtle.backward(60)
my_turtle.right(145)
my_turtle.forward(70)
my_turtle.left(70)
my_turtle.forward(45)
my_turtle.backward(45)
my_turtle.right(110)
my_turtle.forward(70)
my_turtle.left(60)
my_turtle.forward(60)
my_turtle.backward(60)
my_turtle.left(-140)
my_turtle.forward(73)
my_turtle.penup()
my_turtle.goto(-215, 75)
my_turtle.pendown()
my_turtle.right(20)
my_turtle.forward(60)
my_turtle.left(80)
my_turtle.forward(63)
my_turtle.backward(63)
my_turtle.right(110)
my_turtle.forward(70)

#делаем невидимым курсор
my_turtle.ht()
# Необходимо, чтобы окно не закрывалось само, а только по клику
my_turtle.screen.exitonclick()
my_turtle.screen.mainloop()